name: 'CSGOV basic config'
type: module
description: 'Adds various config for the platform'
package: CSGOV
core_version_requirement: ^10
dependencies:
  - antibot:antibot
  - config_rewrite:config_rewrite
  - easy_breadcrumb:easy_breadcrumb
  - extlink:extlink
  - honeypot:honeypot
  - linkit:linkit
  - menu_block:menu_block
  - menu_trail_by_path:menu_trail_by_path
  - metatag:metatag
  - password_policy:password_policy_blacklist
  - password_policy:password_policy_character_types
  - password_policy:password_policy_consecutive
  - password_policy:password_policy_length
  - password_policy:password_policy_username
  - password_policy_pwned:password_policy_pwned
  - pathauto:pathauto
  - rabbit_hole:rabbit_hole
  - responsive_preview:responsive_preview
  - smart_date:smart_date
  - webform:webform
